CREATE TABLE `meditation_progress` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`totalSessions` int DEFAULT 0,
	`totalMinutes` int DEFAULT 0,
	`currentStreak` int DEFAULT 0,
	`longestStreak` int DEFAULT 0,
	`firstSessionDate` timestamp,
	`last7DaysSessions` int DEFAULT 0,
	`last30DaysSessions` int DEFAULT 0,
	`preferredSessionType` varchar(100),
	`preferredDuration` int DEFAULT 20,
	`preferredSoundscape` varchar(50),
	`achievements` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meditation_progress_id` PRIMARY KEY(`id`),
	CONSTRAINT `meditation_progress_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `meditation_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`sessionType` varchar(100) NOT NULL,
	`duration` int NOT NULL,
	`emotionalState` varchar(50),
	`aiGuidanceUsed` boolean DEFAULT true,
	`voiceGuidance` boolean DEFAULT false,
	`soundscape` varchar(50),
	`completionPercentage` int DEFAULT 0,
	`qualityRating` int,
	`notes` text,
	`tokensEarned` int DEFAULT 0,
	`startedAt` timestamp NOT NULL,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meditation_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `retreat_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingNumber` varchar(50) NOT NULL,
	`userId` int,
	`retreatId` int NOT NULL,
	`guestName` varchar(255),
	`guestEmail` varchar(320),
	`guestPhone` varchar(20),
	`accommodationType` enum('private_kuti','shared_room','family') NOT NULL,
	`priceTier` enum('standard','supporter','scholarship') NOT NULL,
	`amountPaid` int NOT NULL,
	`sevaTokensUsed` int DEFAULT 0,
	`dietaryRequirements` text,
	`medicalNotes` text,
	`emergencyContact` text,
	`meditationExperience` text,
	`status` enum('pending','confirmed','waitlist','cancelled','completed') DEFAULT 'pending',
	`arrivalDate` timestamp,
	`departureDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `retreat_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `retreat_bookings_bookingNumber_unique` UNIQUE(`bookingNumber`)
);
--> statement-breakpoint
CREATE TABLE `retreats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`slug` varchar(200) NOT NULL,
	`retreatType` enum('3_day','7_day','10_day_vipassana','14_day','21_day','30_day_teacher','corporate_custom') NOT NULL,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`capacity` int NOT NULL,
	`currentBookings` int DEFAULT 0,
	`teacherId` int NOT NULL,
	`assistantTeachers` text,
	`priceStandard` int NOT NULL,
	`priceSupporter` int NOT NULL,
	`priceScholarship` int NOT NULL,
	`sevaTokenDiscount` int DEFAULT 0,
	`description` text NOT NULL,
	`schedule` text,
	`prerequisites` text,
	`status` enum('announced','open_registration','full','in_progress','completed','cancelled') DEFAULT 'announced',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `retreats_id` PRIMARY KEY(`id`),
	CONSTRAINT `retreats_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `teachers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`bio` text NOT NULL,
	`photoUrl` text,
	`tradition` varchar(100),
	`yearsExperience` int NOT NULL,
	`certifications` text,
	`languages` text,
	`contactEmail` varchar(320),
	`danaPreference` text,
	`availability` text,
	`status` enum('active','inactive','guest') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `teachers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `village_research_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(300) NOT NULL,
	`category` enum('neuroscience','sustainability','contemplative_pedagogy','circular_economy') NOT NULL,
	`leadResearcherId` int NOT NULL,
	`collaborators` text,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`description` text NOT NULL,
	`methodology` text,
	`status` enum('proposed','approved','in_progress','completed','published') DEFAULT 'proposed',
	`publications` text,
	`fundingAmount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `village_research_projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `village_residents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`applicationDate` timestamp NOT NULL,
	`residencyType` enum('long_term','short_term','researcher','family','work_study') NOT NULL,
	`startDate` timestamp,
	`endDate` timestamp,
	`contributionAmount` int DEFAULT 0,
	`sevaTokensEarned` int DEFAULT 0,
	`housingAssignment` varchar(100),
	`workTeam` varchar(100),
	`meditationExperience` text,
	`skills` text,
	`motivation` text,
	`emergencyContact` text,
	`status` enum('applied','interview','trial','accepted','active','alumni','rejected') DEFAULT 'applied',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `village_residents_id` PRIMARY KEY(`id`)
);
