CREATE TABLE `cafe_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`age` int NOT NULL,
	`phone` varchar(20) NOT NULL,
	`email` varchar(320),
	`city` varchar(100) NOT NULL,
	`experience` text,
	`motivation` text NOT NULL,
	`availability` varchar(50) NOT NULL,
	`status` enum('pending','under_review','interview_scheduled','accepted','rejected','withdrawn') DEFAULT 'pending',
	`reviewNotes` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`assignedCafeId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cafe_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cafe_members` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cafeId` int NOT NULL,
	`userId` int,
	`fullName` varchar(255) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`email` varchar(320),
	`role` enum('manager','cook','service','utility','member') DEFAULT 'member',
	`title` varchar(100),
	`joinDate` timestamp,
	`monthlyWage` int,
	`hoursPerWeek` int DEFAULT 45,
	`bio` text,
	`photoUrl` text,
	`status` enum('active','on_leave','inactive') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cafe_members_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cafe_menu_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cafeId` int,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`category` enum('beverage','meal','snack','dessert','special') NOT NULL,
	`communityPrice` int NOT NULL,
	`fairPrice` int NOT NULL,
	`supporterPrice` int NOT NULL,
	`sevaTokenPrice` int NOT NULL,
	`isVegan` boolean DEFAULT false,
	`isGlutenFree` boolean DEFAULT false,
	`isOrganic` boolean DEFAULT true,
	`isSeasonal` boolean DEFAULT false,
	`availableDays` varchar(255),
	`availableTimeStart` varchar(10),
	`availableTimeEnd` varchar(10),
	`imageUrl` text,
	`displayOrder` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cafe_menu_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cafe_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(50) NOT NULL,
	`cafeId` int NOT NULL,
	`userId` int,
	`customerName` varchar(255),
	`totalAmount` int DEFAULT 0,
	`tokensUsed` int DEFAULT 0,
	`paymentMethod` enum('money','seva_tokens','free','mixed') NOT NULL,
	`items` text,
	`notes` text,
	`status` enum('pending','preparing','ready','completed','cancelled') DEFAULT 'pending',
	`orderDate` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cafe_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `cafe_orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `cafes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(100),
	`postalCode` varchar(20),
	`country` varchar(100) DEFAULT 'India',
	`latitude` varchar(50),
	`longitude` varchar(50),
	`mapLink` text,
	`phone` varchar(20),
	`email` varchar(320),
	`hoursOfOperation` text,
	`daysOpen` varchar(255) DEFAULT 'Monday - Saturday',
	`description` text,
	`specialties` text,
	`imageUrl` text,
	`cooperativeMemberCount` int DEFAULT 0,
	`establishedDate` timestamp,
	`status` enum('planning','opening_soon','open','temporarily_closed','closed') DEFAULT 'planning',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cafes_id` PRIMARY KEY(`id`),
	CONSTRAINT `cafes_slug_unique` UNIQUE(`slug`)
);
