CREATE TABLE `oasis_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`location_id` int NOT NULL,
	`room_id` int,
	`booking_type` varchar(50) NOT NULL,
	`therapy_type` varchar(50),
	`scheduled_date` datetime NOT NULL,
	`scheduled_time` varchar(10) NOT NULL,
	`duration` int NOT NULL,
	`status` varchar(20) DEFAULT 'confirmed',
	`group_size` int DEFAULT 1,
	`group_members` json,
	`pricing_tier` varchar(20),
	`amount_paid` decimal(10,2),
	`payment_status` varchar(20) DEFAULT 'pending',
	`reminder_sent` boolean DEFAULT false,
	`reminder_sent_at` datetime,
	`cancelled_at` datetime,
	`cancellation_reason` text,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_bookings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`content_type` varchar(50) NOT NULL,
	`therapy_type` varchar(50) NOT NULL,
	`title` varchar(200) NOT NULL,
	`description` text,
	`duration` int,
	`language` varchar(20) DEFAULT 'hindi',
	`narrator` varchar(100),
	`suitable_for_vata` boolean DEFAULT true,
	`suitable_for_pitta` boolean DEFAULT true,
	`suitable_for_kapha` boolean DEFAULT true,
	`audio_url` varchar(500),
	`video_url` varchar(500),
	`image_url` varchar(500),
	`tags` json,
	`difficulty` varchar(20),
	`times_used` int DEFAULT 0,
	`avg_rating` decimal(3,2),
	`is_active` boolean DEFAULT true,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_content_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_equipment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`location_id` int NOT NULL,
	`room_id` int,
	`equipment_name` varchar(200) NOT NULL,
	`equipment_type` varchar(50) NOT NULL,
	`brand` varchar(100),
	`model` varchar(100),
	`serial_number` varchar(100),
	`purchase_date` datetime,
	`purchase_price` decimal(10,2),
	`warranty_expiry` datetime,
	`status` varchar(20) DEFAULT 'active',
	`last_maintenance_date` datetime,
	`next_maintenance_date` datetime,
	`maintenance_notes` text,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_equipment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_group_participants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`group_session_id` int NOT NULL,
	`user_id` int NOT NULL,
	`registered_at` datetime,
	`attended` boolean DEFAULT false,
	`pricing_tier` varchar(20),
	`amount_paid` decimal(10,2),
	`feedback` text,
	`rating` int,
	`seva_tokens_earned` int DEFAULT 0,
	CONSTRAINT `oasis_group_participants_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_group_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`location_id` int NOT NULL,
	`room_id` int NOT NULL,
	`staff_id` int,
	`session_name` varchar(200) NOT NULL,
	`session_type` varchar(50) NOT NULL,
	`scheduled_date` datetime NOT NULL,
	`scheduled_time` varchar(10) NOT NULL,
	`duration` int NOT NULL,
	`max_participants` int NOT NULL,
	`current_participants` int DEFAULT 0,
	`description` text,
	`community_price` decimal(10,2) DEFAULT 0,
	`fair_price` decimal(10,2),
	`supporter_price` decimal(10,2),
	`status` varchar(20) DEFAULT 'scheduled',
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_group_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_intentions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`session_id` int,
	`intention_text` text NOT NULL,
	`category` varchar(50),
	`is_public` boolean DEFAULT false,
	`target_date` datetime,
	`achieved` boolean DEFAULT false,
	`achieved_date` datetime,
	`check_ins` json,
	`ai_reminders` boolean DEFAULT true,
	`last_reminder_sent` datetime,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_intentions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_memberships` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`membership_tier` varchar(20) NOT NULL,
	`start_date` datetime NOT NULL,
	`end_date` datetime,
	`is_active` boolean DEFAULT true,
	`monthly_fee` decimal(10,2) NOT NULL,
	`payment_method` varchar(50),
	`visits_per_month` int,
	`visits_used` int DEFAULT 0,
	`access_to_therapies` json,
	`can_book_private` boolean DEFAULT false,
	`guest_passes_per_month` int DEFAULT 0,
	`guest_passes_used` int DEFAULT 0,
	`auto_renew` boolean DEFAULT true,
	`next_billing_date` datetime,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_memberships_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_rooms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`location_id` int NOT NULL,
	`room_name` varchar(100) NOT NULL,
	`room_type` varchar(50) NOT NULL,
	`capacity` int NOT NULL,
	`is_active` boolean DEFAULT true,
	`equipment` json,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_rooms_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`location_id` int NOT NULL,
	`session_type` varchar(50) NOT NULL,
	`start_time` datetime NOT NULL,
	`end_time` datetime,
	`duration` int,
	`dosha_type` varchar(20),
	`current_mood` varchar(50),
	`stress_level` int,
	`energy_level` int,
	`health_goals` json,
	`therapies_completed` json,
	`post_stress_level` int,
	`post_energy_level` int,
	`relaxation_score` int,
	`meditation_depth` int,
	`avg_heart_rate` int,
	`avg_breath_rate` int,
	`hrv_improvement` decimal(5,2),
	`user_rating` int,
	`feedback` text,
	`pricing_tier` varchar(20),
	`amount_paid` decimal(10,2),
	`seva_tokens_earned` int DEFAULT 0,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oasis_staff` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`location_id` int NOT NULL,
	`role` varchar(50) NOT NULL,
	`specializations` json,
	`certifications` json,
	`bio` text,
	`photo_url` varchar(500),
	`working_days` json,
	`working_hours` json,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oasis_staff_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `therapy_experiences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`session_id` int NOT NULL,
	`user_id` int NOT NULL,
	`room_id` int NOT NULL,
	`therapy_type` varchar(50) NOT NULL,
	`start_time` datetime NOT NULL,
	`end_time` datetime NOT NULL,
	`duration` int NOT NULL,
	`therapy_data` json,
	`biometric_data` json,
	`ai_insights` text,
	`improvement_score` int,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `therapy_experiences_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wellness_progress` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`primary_dosha` varchar(20),
	`secondary_dosha` varchar(20),
	`dosha_balance` json,
	`last_dosha_assessment` datetime,
	`total_sessions` int DEFAULT 0,
	`total_minutes` int DEFAULT 0,
	`current_streak` int DEFAULT 0,
	`longest_streak` int DEFAULT 0,
	`avg_stress_reduction` decimal(5,2),
	`avg_energy_increase` decimal(5,2),
	`avg_relaxation_score` decimal(5,2),
	`avg_meditation_depth` decimal(5,2),
	`hrv_improvement` decimal(5,2),
	`breath_coherence` decimal(5,2),
	`sleep_quality_score` int,
	`favorite_therapies` json,
	`goals_set` json,
	`achievements_unlocked` json,
	`seva_tokens_earned` int DEFAULT 0,
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wellness_progress_id` PRIMARY KEY(`id`)
);
